# Generated by Django 5.0.6 on 2024-06-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricbill',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electricbill',
            name='rating',
        ),
    ]
